### ISSUE TITLE
Wrong Encode at AddServerRule

### ISSUE THREAD

**Issue by AthallahDzaki** [IS4Code/YSF#147]
![image](https://user-images.githubusercontent.com/44716687/224524037-408c3eae-2dfd-4bf8-a8a7-3784db5bb802.png)
On Windows, The C and D is work very well.

**Comment by IS4Code** [comment]
I have no idea what you are asking about. Show code.

**Comment by AthallahDzaki** [comment]
AddServerRule("Community", "Sampindo");
AddServerRule("Discord", https://discord.com/....");
AddServerRule ("Developer", "Angga");

C will become # and D will become $

**Comment by AthallahDzaki** [comment]
Only happed ant Linux, nor windows

**Comment by IS4Code** [comment]
Closing as not an YSF-related issue, as this is a SA-MP bug. Internally `AddStringVariable` calls `strlwr` on Windows, but on Linux that function has a custom implementation:
```c
char *__cdecl sub_80A9190(char *s)
{
  size_t v1; // eax@1
  size_t v2; // ecx@1

  v1 = strlen(s);
  v2 = 0;
  if ( v1 )
  {
    do
    {
      if ( (unsigned __int8)(s[v2] - 65) <= 25u )
        s[v2] -= 32;
      ++v2;
    }
    while ( v1 > v2 );
  }
  return s;
}
```
As can also be seen in the [source code](/dashr9230/SA-MP/blob/a761bf386d57057a25067c6d49cae06e3e59dfc5/server/main.cpp#L183), it attempts to lowercase letters A - Z, but instead of adding 32, it subtracts it.

The solution ‒ use lowercase, since console variables are supposed to be lowercase:
```c
AddServerRule("community", "Sampindo");
AddServerRule("discord", "https://discord.com/....");
AddServerRule("developer", "Angga");
```
